# GitHub Actions: Build and deploy ASP.NET Core app to Azure Web App
name: Build and deploy ASP.NET Core app to Azure Web App - appointmentmanager

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Necesario para actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/AppointmentManager.sln

      - name: Build
        run: dotnet build ./src/AppointmentManager.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/AppointmentManager.API/AppointmentManager.API.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_139B12A23C5446929098B1F764E5009E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E2A99B1D6B37446898885054ACA23373 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC15368E578D46B4B02AF7456407EC91 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appointmentmanager'
          slot-name: 'Production'
          package: .